version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws --region us-east-2 ecr get-login-password | docker login --username AWS --password-stdin 410205804041.dkr.ecr.us-east-2.amazonaws.com
      - REPOSITORY_URI=410205804041.dkr.ecr.us-east-2.amazonaws.com/snyk_demo
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - kubectl create -f manifests/goof-deployment.yaml
      - kubectl create -f manifests/goof-service.yaml
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
